-- Phase 4 attendance and lesson deduction flow
-- Run this after phase-3-calendar-schema.sql in Supabase SQL Editor

create table if not exists public.schedule_students (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules (id) on delete cascade,
  student_id bigint not null references public.students (id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  unique (schedule_id, student_id)
);

create table if not exists public.lesson_logs (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules (id) on delete restrict,
  teacher_id bigint not null references public.teachers (id) on delete restrict,
  lesson_date date not null,
  lesson_remark text,
  submitted_at timestamptz not null default timezone('utc', now()),
  revision_number integer not null default 1,
  parent_log_id bigint references public.lesson_logs (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  unique (schedule_id, lesson_date, revision_number)
);

create table if not exists public.lesson_log_students (
  id bigint generated by default as identity primary key,
  lesson_log_id bigint not null references public.lesson_logs (id) on delete restrict,
  student_id bigint not null references public.students (id) on delete restrict,
  attendance_status text not null check (attendance_status in ('present', 'absent', 'leave')),
  created_at timestamptz not null default timezone('utc', now()),
  unique (lesson_log_id, student_id)
);

create table if not exists public.student_lesson_ledger (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete restrict,
  lesson_log_id bigint not null references public.lesson_logs (id) on delete restrict,
  delta_lessons integer not null,
  reason text not null,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.schedule_students enable row level security;
alter table public.lesson_logs enable row level security;
alter table public.lesson_log_students enable row level security;
alter table public.student_lesson_ledger enable row level security;

drop policy if exists "temp_dev_schedule_students_select" on public.schedule_students;
create policy "temp_dev_schedule_students_select"
on public.schedule_students
for select
to anon, authenticated
using (true);

drop policy if exists "temp_dev_schedule_students_insert" on public.schedule_students;
create policy "temp_dev_schedule_students_insert"
on public.schedule_students
for insert
to anon, authenticated
with check (true);

drop policy if exists "temp_dev_schedule_students_update" on public.schedule_students;
create policy "temp_dev_schedule_students_update"
on public.schedule_students
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "temp_dev_lesson_logs_select" on public.lesson_logs;
create policy "temp_dev_lesson_logs_select"
on public.lesson_logs
for select
to anon, authenticated
using (true);

drop policy if exists "temp_dev_lesson_log_students_select" on public.lesson_log_students;
create policy "temp_dev_lesson_log_students_select"
on public.lesson_log_students
for select
to anon, authenticated
using (true);

drop policy if exists "temp_dev_student_lesson_ledger_select" on public.student_lesson_ledger;
create policy "temp_dev_student_lesson_ledger_select"
on public.student_lesson_ledger
for select
to anon, authenticated
using (true);

insert into public.schedule_students (schedule_id, student_id)
select s.id, st.id
from public.schedules s
join public.students st on st.full_name = 'Olivia Tan'
where s.title = 'Olivia Tan 1-to-1 Science'
on conflict (schedule_id, student_id) do nothing;

insert into public.schedule_students (schedule_id, student_id)
select s.id, st.id
from public.schedules s
join public.students st on st.full_name = 'Ethan Lim'
where s.title = 'Ethan Lim Math Intensive'
on conflict (schedule_id, student_id) do nothing;

insert into public.schedule_students (schedule_id, student_id)
select s.id, st.id
from public.schedules s
join public.students st on st.full_name = 'Chloe Wong'
where s.title = 'Chloe Wong Replacement Class'
on conflict (schedule_id, student_id) do nothing;

insert into public.schedule_students (schedule_id, student_id)
select s.id, st.id
from public.schedules s
join public.students st on st.full_name = 'Ryan Koh'
where s.title = 'Ryan Koh Catch-up Session'
on conflict (schedule_id, student_id) do nothing;

create or replace function public.submit_lesson_attendance(
  p_schedule_id bigint,
  p_occurrence_date date,
  p_teacher_id bigint,
  p_lesson_remark text,
  p_attendance jsonb
)
returns table (
  lesson_log_id bigint,
  revision_number integer,
  updated_student_count integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_schedule public.schedules%rowtype;
  v_teacher public.teachers%rowtype;
  v_previous_log public.lesson_logs%rowtype;
  v_next_revision integer := 1;
  v_new_log_id bigint;
  v_updated_count integer := 0;
  v_item jsonb;
  v_student_id bigint;
  v_new_status text;
  v_prev_status text;
  v_prev_delta integer;
  v_new_delta integer;
  v_net_delta integer;
begin
  select *
  into v_schedule
  from public.schedules
  where id = p_schedule_id;

  if not found then
    raise exception 'Schedule not found.';
  end if;

  select *
  into v_teacher
  from public.teachers
  where id = p_teacher_id;

  if not found then
    raise exception 'Teacher not found.';
  end if;

  if v_teacher.role = 'teacher' and v_schedule.teacher_id <> p_teacher_id then
    raise exception 'Teacher can only submit attendance for assigned schedules.';
  end if;

  if jsonb_typeof(p_attendance) <> 'array' then
    raise exception 'Attendance payload must be an array.';
  end if;

  select *
  into v_previous_log
  from public.lesson_logs
  where schedule_id = p_schedule_id
    and lesson_date = p_occurrence_date
  order by revision_number desc
  limit 1;

  if found then
    if timezone('utc', now()) > v_previous_log.submitted_at + interval '24 hours' then
      raise exception 'Attendance can only be modified within 24 hours.';
    end if;

    v_next_revision := v_previous_log.revision_number + 1;
  end if;

  insert into public.lesson_logs (
    schedule_id,
    teacher_id,
    lesson_date,
    lesson_remark,
    revision_number,
    parent_log_id
  )
  values (
    p_schedule_id,
    p_teacher_id,
    p_occurrence_date,
    p_lesson_remark,
    v_next_revision,
    case when v_next_revision > 1 then v_previous_log.id else null end
  )
  returning id into v_new_log_id;

  for v_item in
    select value from jsonb_array_elements(p_attendance)
  loop
    v_student_id := (v_item ->> 'student_id')::bigint;
    v_new_status := v_item ->> 'status';

    if v_new_status not in ('present', 'absent', 'leave') then
      raise exception 'Invalid attendance status for student %', v_student_id;
    end if;

    if not exists (
      select 1
      from public.schedule_students ss
      where ss.schedule_id = p_schedule_id
        and ss.student_id = v_student_id
        and ss.is_active = true
    ) then
      raise exception 'Student % is not assigned to this schedule.', v_student_id;
    end if;

    insert into public.lesson_log_students (
      lesson_log_id,
      student_id,
      attendance_status
    )
    values (
      v_new_log_id,
      v_student_id,
      v_new_status
    );

    if v_next_revision > 1 then
      select attendance_status
      into v_prev_status
      from public.lesson_log_students
      where lesson_log_id = v_previous_log.id
        and student_id = v_student_id;
    else
      v_prev_status := null;
    end if;

    v_prev_delta := case when v_prev_status = 'present' then -1 else 0 end;
    v_new_delta := case when v_new_status = 'present' then -1 else 0 end;
    v_net_delta := v_new_delta - v_prev_delta;

    if v_net_delta <> 0 then
      update public.students
      set remaining_hours = remaining_hours + v_net_delta
      where id = v_student_id;

      insert into public.student_lesson_ledger (
        student_id,
        lesson_log_id,
        delta_lessons,
        reason
      )
      values (
        v_student_id,
        v_new_log_id,
        v_net_delta,
        case
          when v_net_delta = -1 then 'attendance_present_deduction'
          when v_net_delta = 1 then 'attendance_revision_reversal'
          else 'attendance_adjustment'
        end
      );

      v_updated_count := v_updated_count + 1;
    end if;
  end loop;

  return query
  select v_new_log_id, v_next_revision, v_updated_count;
end;
$$;
