-- Phase 5 student creation and renewal ledger
-- Run this after phase-4-attendance-schema.sql in Supabase SQL Editor

create table if not exists public.student_admin_ledger (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete restrict,
  action_type text not null check (
    action_type in (
      'student_created',
      'hours_added',
      'lesson_expiry_updated',
      'account_fee_expiry_updated',
      'mirai_club_expiry_updated'
    )
  ),
  delta_hours integer,
  old_date date,
  new_date date,
  remark text,
  actor_teacher_id bigint references public.teachers (id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.student_admin_ledger enable row level security;

drop policy if exists "temp_dev_student_admin_ledger_select" on public.student_admin_ledger;
create policy "temp_dev_student_admin_ledger_select"
on public.student_admin_ledger
for select
to anon, authenticated
using (true);

create or replace function public.create_student_record(
  p_full_name text,
  p_teacher_id bigint,
  p_initial_hours integer,
  p_lesson_expiry_date date,
  p_account_fee_expiry_date date,
  p_mirai_club_expiry_date date,
  p_notes text,
  p_actor_teacher_id bigint default null
)
returns table (
  student_id bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student_id bigint;
  v_initial_hours integer := greatest(coalesce(p_initial_hours, 0), 0);
begin
  if coalesce(trim(p_full_name), '') = '' then
    raise exception 'Student full name is required.';
  end if;

  if p_teacher_id is not null and not exists (
    select 1
    from public.teachers
    where id = p_teacher_id
  ) then
    raise exception 'Assigned teacher not found.';
  end if;

  if p_actor_teacher_id is not null and not exists (
    select 1
    from public.teachers
    where id = p_actor_teacher_id
  ) then
    raise exception 'Actor teacher not found.';
  end if;

  insert into public.students (
    teacher_id,
    full_name,
    remaining_hours,
    lesson_expiry_date,
    account_fee_expiry_date,
    mirai_club_expiry_date,
    notes,
    is_active
  )
  values (
    p_teacher_id,
    trim(p_full_name),
    v_initial_hours,
    p_lesson_expiry_date,
    p_account_fee_expiry_date,
    p_mirai_club_expiry_date,
    nullif(trim(coalesce(p_notes, '')), ''),
    true
  )
  returning id into v_student_id;

  insert into public.student_admin_ledger (
    student_id,
    action_type,
    delta_hours,
    remark,
    actor_teacher_id
  )
  values (
    v_student_id,
    'student_created',
    v_initial_hours,
    coalesce(nullif(trim(coalesce(p_notes, '')), ''), 'Initial student record created.'),
    p_actor_teacher_id
  );

  insert into public.student_admin_ledger (
    student_id,
    action_type,
    old_date,
    new_date,
    remark,
    actor_teacher_id
  )
  values
    (
      v_student_id,
      'lesson_expiry_updated',
      null,
      p_lesson_expiry_date,
      'Initial lesson expiry set.',
      p_actor_teacher_id
    ),
    (
      v_student_id,
      'account_fee_expiry_updated',
      null,
      p_account_fee_expiry_date,
      'Initial account fee expiry set.',
      p_actor_teacher_id
    ),
    (
      v_student_id,
      'mirai_club_expiry_updated',
      null,
      p_mirai_club_expiry_date,
      'Initial Mirai Club expiry set.',
      p_actor_teacher_id
    );

  return query
  select v_student_id;
end;
$$;

create or replace function public.renew_student_record(
  p_student_id bigint,
  p_add_hours integer,
  p_new_lesson_expiry_date date,
  p_new_account_fee_expiry_date date,
  p_new_mirai_club_expiry_date date,
  p_remark text,
  p_actor_teacher_id bigint default null
)
returns table (
  student_id bigint,
  remaining_hours integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_student public.students%rowtype;
  v_add_hours integer := greatest(coalesce(p_add_hours, 0), 0);
  v_next_lesson_expiry date;
  v_next_account_fee_expiry date;
  v_next_mirai_club_expiry date;
  v_next_remaining_hours integer;
  v_remark text := nullif(trim(coalesce(p_remark, '')), '');
begin
  select *
  into v_student
  from public.students
  where id = p_student_id;

  if not found then
    raise exception 'Student not found.';
  end if;

  if p_actor_teacher_id is not null and not exists (
    select 1
    from public.teachers
    where id = p_actor_teacher_id
  ) then
    raise exception 'Actor teacher not found.';
  end if;

  v_next_lesson_expiry := coalesce(p_new_lesson_expiry_date, v_student.lesson_expiry_date);
  v_next_account_fee_expiry := coalesce(p_new_account_fee_expiry_date, v_student.account_fee_expiry_date);
  v_next_mirai_club_expiry := coalesce(p_new_mirai_club_expiry_date, v_student.mirai_club_expiry_date);
  v_next_remaining_hours := v_student.remaining_hours + v_add_hours;

  if v_add_hours = 0
    and v_next_lesson_expiry = v_student.lesson_expiry_date
    and v_next_account_fee_expiry = v_student.account_fee_expiry_date
    and v_next_mirai_club_expiry = v_student.mirai_club_expiry_date then
    raise exception 'No renewal changes were submitted.';
  end if;

  update public.students
  set
    remaining_hours = v_next_remaining_hours,
    lesson_expiry_date = v_next_lesson_expiry,
    account_fee_expiry_date = v_next_account_fee_expiry,
    mirai_club_expiry_date = v_next_mirai_club_expiry
  where id = p_student_id;

  if v_add_hours > 0 then
    insert into public.student_admin_ledger (
      student_id,
      action_type,
      delta_hours,
      remark,
      actor_teacher_id
    )
    values (
      p_student_id,
      'hours_added',
      v_add_hours,
      coalesce(v_remark, 'Hours renewed by admin.'),
      p_actor_teacher_id
    );
  end if;

  if v_next_lesson_expiry <> v_student.lesson_expiry_date then
    insert into public.student_admin_ledger (
      student_id,
      action_type,
      old_date,
      new_date,
      remark,
      actor_teacher_id
    )
    values (
      p_student_id,
      'lesson_expiry_updated',
      v_student.lesson_expiry_date,
      v_next_lesson_expiry,
      coalesce(v_remark, 'Lesson expiry renewed by admin.'),
      p_actor_teacher_id
    );
  end if;

  if v_next_account_fee_expiry <> v_student.account_fee_expiry_date then
    insert into public.student_admin_ledger (
      student_id,
      action_type,
      old_date,
      new_date,
      remark,
      actor_teacher_id
    )
    values (
      p_student_id,
      'account_fee_expiry_updated',
      v_student.account_fee_expiry_date,
      v_next_account_fee_expiry,
      coalesce(v_remark, 'Account fee expiry renewed by admin.'),
      p_actor_teacher_id
    );
  end if;

  if v_next_mirai_club_expiry <> v_student.mirai_club_expiry_date then
    insert into public.student_admin_ledger (
      student_id,
      action_type,
      old_date,
      new_date,
      remark,
      actor_teacher_id
    )
    values (
      p_student_id,
      'mirai_club_expiry_updated',
      v_student.mirai_club_expiry_date,
      v_next_mirai_club_expiry,
      coalesce(v_remark, 'Mirai Club expiry renewed by admin.'),
      p_actor_teacher_id
    );
  end if;

  return query
  select p_student_id, v_next_remaining_hours;
end;
$$;
