-- Phase 3 schema for calendar schedules and role-aware timetable viewing
-- Run this after phase-2-schema.sql in Supabase SQL Editor

insert into public.teachers (
  username,
  password_hash,
  full_name,
  email,
  role
) values
  (
    'teacher_luna',
    '$2b$12$replace_with_real_hash_before_production',
    'Luna Tan',
    'luna@example.com',
    'teacher'
  ),
  (
    'teacher_aaron',
    '$2b$12$replace_with_real_hash_before_production',
    'Aaron Lee',
    'aaron@example.com',
    'teacher'
  )
on conflict (username) do update
set
  full_name = excluded.full_name,
  email = excluded.email,
  role = excluded.role;

update public.students
set teacher_id = (
  select id from public.teachers where username = 'teacher_luna' limit 1
)
where full_name in ('Olivia Tan', 'Chloe Wong');

update public.students
set teacher_id = (
  select id from public.teachers where username = 'teacher_aaron' limit 1
)
where full_name in ('Ethan Lim', 'Ryan Koh');

create table if not exists public.schedules (
  id bigint generated by default as identity primary key,
  teacher_id bigint not null references public.teachers (id) on delete restrict,
  student_id bigint references public.students (id) on delete set null,
  title text not null,
  event_type text not null check (event_type in ('regular', 'replacement')),
  recurrence_type text not null default 'none' check (recurrence_type in ('weekly', 'none')),
  day_of_week smallint check (day_of_week between 0 and 6),
  scheduled_date date,
  start_time time not null,
  end_time time not null,
  start_recur date,
  end_recur date,
  status text not null default 'active' check (status in ('active', 'cancelled')),
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (end_time > start_time),
  check (
    (
      event_type = 'regular'
      and recurrence_type = 'weekly'
      and day_of_week is not null
      and start_recur is not null
      and scheduled_date is null
    )
    or
    (
      event_type = 'replacement'
      and recurrence_type = 'none'
      and scheduled_date is not null
      and day_of_week is null
    )
  )
);

drop trigger if exists set_schedules_updated_at on public.schedules;
create trigger set_schedules_updated_at
before update on public.schedules
for each row
execute function public.set_current_timestamp_updated_at();

alter table public.schedules enable row level security;

drop policy if exists "temp_dev_teachers_select" on public.teachers;
create policy "temp_dev_teachers_select"
on public.teachers
for select
to anon, authenticated
using (true);

drop policy if exists "temp_dev_schedules_select" on public.schedules;
create policy "temp_dev_schedules_select"
on public.schedules
for select
to anon, authenticated
using (true);

drop policy if exists "temp_dev_schedules_insert" on public.schedules;
create policy "temp_dev_schedules_insert"
on public.schedules
for insert
to anon, authenticated
with check (true);

drop policy if exists "temp_dev_schedules_update" on public.schedules;
create policy "temp_dev_schedules_update"
on public.schedules
for update
to anon, authenticated
using (true)
with check (true);

insert into public.schedules (
  teacher_id,
  student_id,
  title,
  event_type,
  recurrence_type,
  day_of_week,
  start_time,
  end_time,
  start_recur,
  end_recur,
  notes
)
select
  teacher.id,
  student.id,
  seed.title,
  'regular',
  'weekly',
  seed.day_of_week,
  seed.start_time,
  seed.end_time,
  seed.start_recur,
  seed.end_recur,
  seed.notes
from (
  values
    ('Olivia Tan 1-to-1 Science', 'teacher_luna', 'Olivia Tan', 2, time '19:30', time '21:30', date '2026-07-07', date '2026-12-29', 'Recurring regular class every Tuesday'),
    ('Ethan Lim Math Intensive', 'teacher_aaron', 'Ethan Lim', 4, time '16:00', time '18:00', date '2026-07-09', date '2026-12-31', 'Recurring regular class every Thursday')
) as seed (
  title,
  teacher_username,
  student_name,
  day_of_week,
  start_time,
  end_time,
  start_recur,
  end_recur,
  notes
)
join public.teachers teacher on teacher.username = seed.teacher_username
left join public.students student on student.full_name = seed.student_name
where not exists (
  select 1
  from public.schedules existing
  where existing.title = seed.title
    and existing.teacher_id = teacher.id
    and existing.event_type = 'regular'
);

insert into public.schedules (
  teacher_id,
  student_id,
  title,
  event_type,
  recurrence_type,
  scheduled_date,
  start_time,
  end_time,
  notes
)
select
  teacher.id,
  student.id,
  seed.title,
  'replacement',
  'none',
  seed.scheduled_date,
  seed.start_time,
  seed.end_time,
  seed.notes
from (
  values
    ('Chloe Wong Replacement Class', 'teacher_luna', 'Chloe Wong', date '2026-07-05', time '14:00', time '16:00', 'One-off replacement class'),
    ('Ryan Koh Catch-up Session', 'teacher_aaron', 'Ryan Koh', date '2026-07-11', time '10:00', time '11:30', 'Replacement session after missed regular class')
) as seed (
  title,
  teacher_username,
  student_name,
  scheduled_date,
  start_time,
  end_time,
  notes
)
join public.teachers teacher on teacher.username = seed.teacher_username
left join public.students student on student.full_name = seed.student_name
where not exists (
  select 1
  from public.schedules existing
  where existing.title = seed.title
    and existing.teacher_id = teacher.id
    and existing.event_type = 'replacement'
);
