-- Course packages.
--
-- A package is what a parent signs up for: how many classes, over how many
-- months, and whether the yearly Account Fee and Mirai AI Club Fee apply.
-- kind groups them for the Students filters:
--   trial   - Trial 1 Month (tries the regular class after HOA), no fees
--   regular - 3 / 6 / 12 months, with fees
--   camp    - Mirai AI Online Holiday Camp, no fees
-- HOA itself stays a trial-slot booking, not a package. No prices are kept.
-- Admin adds, renames and hides packages; they are never deleted, so the
-- students and enrollments that used one keep it.
--
-- students.package_id is the package a student is on now; every sign-up or
-- renewal adds a row to student_enrollments, which is the history
-- (e.g. Trial 1 Month in October, then 6 Months in November).
--
-- Camp classes get their own classroom category.

create table if not exists public.packages (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(btrim(name)) between 1 and 60),
  kind text not null check (kind in ('trial', 'regular', 'camp')),
  class_count integer not null check (class_count between 1 and 500),
  duration_months integer not null check (duration_months between 1 and 36),
  includes_fees boolean not null default false,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists packages_name_key on public.packages (lower(btrim(name)));

insert into public.packages (name, kind, class_count, duration_months, includes_fees, sort_order)
values
  ('Trial 1 Month', 'trial', 4, 1, false, 10),
  ('3 Months', 'regular', 12, 3, true, 20),
  ('6 Months', 'regular', 24, 6, true, 30),
  ('12 Months', 'regular', 48, 12, true, 40),
  ('Holiday Camp', 'camp', 12, 3, false, 50)
on conflict do nothing;

alter table public.packages enable row level security;

-- Package names show next to students for anyone who can see students.
create policy packages_select_signed_in on public.packages
for select to authenticated using (true);

create policy packages_insert_admin on public.packages
for insert to authenticated with check ((select public.is_admin()));

create policy packages_update_admin on public.packages
for update to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select, insert, update on public.packages to authenticated;

alter table public.students
  add column if not exists package_id bigint references public.packages (id);

create index if not exists idx_students_package_id on public.students (package_id);

create table if not exists public.student_enrollments (
  id bigint generated by default as identity primary key,
  student_id bigint not null references public.students (id) on delete cascade,
  package_id bigint not null references public.packages (id),
  start_date date not null,
  end_date date not null,
  class_count integer not null check (class_count between 0 and 500),
  remark text,
  actor_teacher_id bigint references public.teachers (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  check (end_date >= start_date)
);

create index if not exists idx_student_enrollments_student
on public.student_enrollments (student_id, start_date desc);

alter table public.student_enrollments enable row level security;

-- Same reach as the student's admin ledger. Written only by the RPC below.
create policy student_enrollments_select_scoped on public.student_enrollments
for select to authenticated
using (
  (select public.can_view_classes())
  or exists (
    select 1 from public.students st
    where st.id = student_enrollments.student_id
      and (
        st.teacher_id = (select public.current_teacher_id())
        or st.classroom_id in (
          select c.id from public.classrooms c
          where c.teacher_id = (select public.current_teacher_id())
        )
      )
  )
);

grant select on public.student_enrollments to authenticated;

alter table public.classrooms drop constraint classrooms_category_check;
alter table public.classrooms
  add constraint classrooms_category_check check (category in ('regular', 'trial', 'camp'));

-- Signs a student up for a package: adds its classes, sets the new expiry
-- dates (worked out by the app from the package, and editable there), and
-- records the enrollment. The hours and dates go through renew_student_record
-- so the admin ledger keeps the same entries as a manual renewal.
create or replace function public.enroll_student_package(
  p_student_id bigint,
  p_package_id bigint,
  p_start_date date,
  p_class_count integer,
  p_lesson_expiry_date date,
  p_account_fee_expiry_date date,
  p_mirai_club_expiry_date date,
  p_remark text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_package public.packages%rowtype;
  v_enrollment_id bigint;
  v_remark text := nullif(trim(coalesce(p_remark, '')), '');
begin
  if not public.has_permission('students', 'edit') then
    raise exception 'Your account is not allowed to enroll students.';
  end if;

  select * into v_package from public.packages where id = p_package_id;
  if not found or not v_package.is_active then
    raise exception 'Pick an active package.';
  end if;

  if not exists (
    select 1 from public.students where id = p_student_id and student_type = 'regular'
  ) then
    raise exception 'Only regular students can be enrolled in a package.';
  end if;

  if p_start_date is null or p_lesson_expiry_date is null or p_lesson_expiry_date < p_start_date then
    raise exception 'The package must end on or after the day it starts.';
  end if;

  if coalesce(p_class_count, 0) < 0 or p_class_count > 500 then
    raise exception 'Classes must be between 0 and 500.';
  end if;

  perform public.renew_student_record(
    p_student_id,
    p_class_count,
    p_lesson_expiry_date,
    p_account_fee_expiry_date,
    p_mirai_club_expiry_date,
    coalesce(v_remark, v_package.name || ' package.')
  );

  insert into public.student_enrollments (
    student_id, package_id, start_date, end_date, class_count, remark, actor_teacher_id
  )
  values (
    p_student_id, p_package_id, p_start_date, p_lesson_expiry_date, p_class_count,
    v_remark, public.current_teacher_id()
  )
  returning id into v_enrollment_id;

  update public.students set package_id = p_package_id where id = p_student_id;

  return v_enrollment_id;
end;
$$;

-- Tags a student with the package they are already on, without adding
-- classes or touching dates. For students who joined before packages existed.
create or replace function public.set_student_package(p_student_id bigint, p_package_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.has_permission('students', 'edit') then
    raise exception 'Your account is not allowed to change a student''s package.';
  end if;

  if p_package_id is not null and not exists (select 1 from public.packages where id = p_package_id) then
    raise exception 'Package not found.';
  end if;

  update public.students
  set package_id = p_package_id
  where id = p_student_id and student_type = 'regular';

  if not found then
    raise exception 'Only regular students can have a package.';
  end if;
end;
$$;

revoke all on function public.enroll_student_package(bigint, bigint, date, integer, date, date, date, text) from public, anon;
revoke all on function public.set_student_package(bigint, bigint) from public, anon;
grant execute on function public.enroll_student_package(bigint, bigint, date, integer, date, date, date, text) to authenticated;
grant execute on function public.set_student_package(bigint, bigint) to authenticated;
