-- Admin activity history, record editing, and classroom archiving.

alter table public.classrooms
add column if not exists archived_at timestamptz;

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  actor_teacher_id bigint references public.teachers (id) on delete set null,
  action_type text not null,
  entity_type text not null check (
    entity_type in ('student', 'teacher', 'classroom', 'schedule')
  ),
  entity_id bigint,
  entity_label text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_admin_activity_logs_created_at
on public.admin_activity_logs (created_at desc);

create index if not exists idx_admin_activity_logs_actor_teacher_id
on public.admin_activity_logs (actor_teacher_id);

alter table public.admin_activity_logs enable row level security;

drop policy if exists "temp_dev_admin_activity_logs_select" on public.admin_activity_logs;
create policy "temp_dev_admin_activity_logs_select"
on public.admin_activity_logs
for select
to anon, authenticated
using (true);

-- No update or delete policy is intentionally provided. Activity history is immutable.

create or replace function public.record_admin_activity(
  p_actor_teacher_id bigint,
  p_action_type text,
  p_entity_type text,
  p_entity_id bigint,
  p_entity_label text,
  p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_log_id bigint;
begin
  if p_entity_type not in ('student', 'teacher', 'classroom', 'schedule') then
    raise exception 'Unsupported activity entity type.';
  end if;

  insert into public.admin_activity_logs (
    actor_teacher_id,
    action_type,
    entity_type,
    entity_id,
    entity_label,
    details
  ) values (
    p_actor_teacher_id,
    trim(p_action_type),
    p_entity_type,
    p_entity_id,
    trim(p_entity_label),
    coalesce(p_details, '{}'::jsonb)
  )
  returning id into v_log_id;

  return v_log_id;
end;
$$;

create or replace function public.update_student_record(
  p_student_id bigint,
  p_full_name text,
  p_teacher_id bigint,
  p_classroom_id bigint,
  p_notes text,
  p_actor_teacher_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_previous public.students%rowtype;
  v_classroom_teacher_id bigint;
begin
  select * into v_previous
  from public.students
  where id = p_student_id
  for update;

  if not found then
    raise exception 'Student record not found.';
  end if;

  if coalesce(trim(p_full_name), '') = '' then
    raise exception 'Student full name is required.';
  end if;

  if p_classroom_id is not null then
    select teacher_id into v_classroom_teacher_id
    from public.classrooms
    where id = p_classroom_id
      and status = 'active';

    if not found then
      raise exception 'Selected classroom is not active.';
    end if;
  end if;

  update public.students
  set
    full_name = trim(p_full_name),
    classroom_id = p_classroom_id,
    teacher_id = coalesce(v_classroom_teacher_id, p_teacher_id),
    notes = nullif(trim(coalesce(p_notes, '')), '')
  where id = p_student_id;

  perform public.record_admin_activity(
    p_actor_teacher_id,
    'student_updated',
    'student',
    p_student_id,
    trim(p_full_name),
    jsonb_build_object(
      'previous_classroom_id', v_previous.classroom_id,
      'new_classroom_id', p_classroom_id,
      'previous_teacher_id', v_previous.teacher_id,
      'new_teacher_id', coalesce(v_classroom_teacher_id, p_teacher_id)
    )
  );
end;
$$;

create or replace function public.update_teacher_record(
  p_teacher_id bigint,
  p_username text,
  p_full_name text,
  p_email text,
  p_phone text,
  p_role text,
  p_actor_teacher_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_previous public.teachers%rowtype;
begin
  select * into v_previous
  from public.teachers
  where id = p_teacher_id
    and is_active = true
  for update;

  if not found then
    raise exception 'Teacher record not found.';
  end if;

  if coalesce(trim(p_username), '') = '' then
    raise exception 'Username is required.';
  end if;

  if coalesce(trim(p_full_name), '') = '' then
    raise exception 'Teacher full name is required.';
  end if;

  if p_role not in ('admin', 'teacher') then
    raise exception 'Teacher role must be admin or teacher.';
  end if;

  if v_previous.username = 'admin_demo' and (
    trim(p_username) <> 'admin_demo' or p_role <> 'admin'
  ) then
    raise exception 'The bootstrap Admin username and role are protected.';
  end if;

  update public.teachers
  set
    username = trim(p_username),
    full_name = trim(p_full_name),
    email = nullif(trim(coalesce(p_email, '')), ''),
    phone = nullif(trim(coalesce(p_phone, '')), ''),
    role = p_role
  where id = p_teacher_id;

  perform public.record_admin_activity(
    p_actor_teacher_id,
    'teacher_updated',
    'teacher',
    p_teacher_id,
    trim(p_full_name),
    jsonb_build_object(
      'previous_username', v_previous.username,
      'new_username', trim(p_username),
      'previous_role', v_previous.role,
      'new_role', p_role
    )
  );
end;
$$;

create or replace function public.archive_classroom(
  p_classroom_id bigint,
  p_actor_teacher_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_classroom public.classrooms%rowtype;
begin
  select * into v_classroom
  from public.classrooms
  where id = p_classroom_id
  for update;

  if not found then
    raise exception 'Classroom not found.';
  end if;

  update public.schedules
  set status = 'cancelled'
  where classroom_id = p_classroom_id
    and status = 'active';

  update public.classrooms
  set status = 'archived', archived_at = timezone('utc', now())
  where id = p_classroom_id;

  perform public.record_admin_activity(
    p_actor_teacher_id,
    'classroom_archived',
    'classroom',
    p_classroom_id,
    v_classroom.name,
    jsonb_build_object(
      'age_group', v_classroom.age_group,
      'program_level', v_classroom.program_level,
      'teacher_id', v_classroom.teacher_id
    )
  );
end;
$$;

create or replace function public.restore_classroom(
  p_classroom_id bigint,
  p_actor_teacher_id bigint default null
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_classroom public.classrooms%rowtype;
begin
  select * into v_classroom
  from public.classrooms
  where id = p_classroom_id
    and status = 'archived'
  for update;

  if not found then
    raise exception 'Archived classroom not found.';
  end if;

  update public.classrooms
  set status = 'active', archived_at = null
  where id = p_classroom_id;

  perform public.record_admin_activity(
    p_actor_teacher_id,
    'classroom_restored',
    'classroom',
    p_classroom_id,
    v_classroom.name,
    '{}'::jsonb
  );
end;
$$;

grant execute on function public.record_admin_activity(bigint, text, text, bigint, text, jsonb)
to anon, authenticated;
grant execute on function public.update_student_record(bigint, text, bigint, bigint, text, bigint)
to anon, authenticated;
grant execute on function public.update_teacher_record(bigint, text, text, text, text, text, bigint)
to anon, authenticated;
grant execute on function public.archive_classroom(bigint, bigint)
to anon, authenticated;
grant execute on function public.restore_classroom(bigint, bigint)
to anon, authenticated;
