-- Lead sources and PICs the admin can add, rename and hide.
--
-- lead_options holds both lists (kind 'source' or 'pic'). Leads point at an
-- option by id, so renaming one updates every lead at once, and hiding one
-- (is_active = false) only drops it from the pickers: leads and reports that
-- use it keep it. Options are never deleted.
--
-- The five fixed sources become the first options; each keeps its old key in
-- legacy_key so existing leads are linked, and so leads.source (still set by
-- server functions such as book_trial_slot, which writes 'other') keeps
-- mapping to a source_id through the trigger below. leads.source itself is
-- no longer read by the app.

create table if not exists public.lead_options (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('source', 'pic')),
  label text not null check (char_length(btrim(label)) between 1 and 60),
  is_active boolean not null default true,
  legacy_key text unique,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists lead_options_kind_label_key
on public.lead_options (kind, lower(btrim(label)));

insert into public.lead_options (kind, label, legacy_key)
values
  ('source', 'Walk-in', 'walk_in'),
  ('source', 'Referral', 'referral'),
  ('source', 'Social Media', 'social_media'),
  ('source', 'Advertisement', 'advertisement'),
  ('source', 'Other', 'other')
on conflict (legacy_key) do nothing;

alter table public.lead_options enable row level security;

create policy "lead_options_select_admin"
on public.lead_options
for select
to authenticated
using (public.is_admin());

create policy "lead_options_insert_admin"
on public.lead_options
for insert
to authenticated
with check (public.is_admin());

create policy "lead_options_update_admin"
on public.lead_options
for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

grant select, insert, update on public.lead_options to authenticated;

alter table public.leads
  add column if not exists source_id bigint references public.lead_options (id),
  add column if not exists pic_id bigint references public.lead_options (id);

create index if not exists idx_leads_source_id on public.leads (source_id);
create index if not exists idx_leads_pic_id on public.leads (pic_id);

update public.leads l
set source_id = o.id
from public.lead_options o
where o.legacy_key = l.source
  and l.source_id is null;

-- Fills source_id from the legacy key when a writer only sets leads.source,
-- and makes sure source_id / pic_id point at the right kind of option.
create or replace function public.leads_check_options()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.source_id is null then
    select id into new.source_id
    from public.lead_options
    where legacy_key = coalesce(new.source, 'other');
  end if;

  if new.source_id is not null and not exists (
    select 1 from public.lead_options where id = new.source_id and kind = 'source'
  ) then
    raise exception 'That is not a lead source.';
  end if;

  if new.pic_id is not null and not exists (
    select 1 from public.lead_options where id = new.pic_id and kind = 'pic'
  ) then
    raise exception 'That is not a PIC.';
  end if;

  return new;
end;
$$;

revoke all on function public.leads_check_options() from public, anon, authenticated;

drop trigger if exists leads_check_options on public.leads;
create trigger leads_check_options
before insert or update of source, source_id, pic_id on public.leads
for each row execute function public.leads_check_options();
