-- Simple sales pipeline: leads coming into the school, tracked through a
-- fixed set of stages until they either convert into a real student record
-- or are marked lost. Mirrors the existing students/classrooms table style.

create table public.leads (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  email text,
  source text not null default 'other',
  status text not null default 'new',
  interested_age_group text,
  notes text,
  follow_up_date date,
  converted_student_id bigint references public.students(id) on delete set null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  updated_at timestamptz not null default timezone('utc'::text, now()),
  constraint leads_source_check check (
    source = any (array['walk_in', 'referral', 'social_media', 'advertisement', 'other'])
  ),
  constraint leads_status_check check (
    status = any (
      array['new', 'contacted', 'trial_scheduled', 'trial_completed', 'converted', 'lost']
    )
  ),
  constraint leads_interested_age_group_check check (
    interested_age_group is null
    or interested_age_group = any (
      array['6-8 Years Old', '9-11 Years Old', '12-14 Years Old', '15-17 Years Old']
    )
  )
);

alter table public.leads enable row level security;

create policy temp_dev_leads_select on public.leads for select using (true);
create policy temp_dev_leads_insert on public.leads for insert with check (true);
create policy temp_dev_leads_update on public.leads for update using (true) with check (true);

create trigger set_leads_updated_at
  before update on public.leads
  for each row execute function set_current_timestamp_updated_at();

-- Extend the shared activity logger to accept 'lead' entities (lead created,
-- status changed, converted to a student) alongside the existing types.
create or replace function public.record_admin_activity(
  p_actor_teacher_id bigint,
  p_action_type text,
  p_entity_type text,
  p_entity_id bigint,
  p_entity_label text,
  p_details jsonb default '{}'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path to 'public'
as $function$
declare
  v_log_id bigint;
begin
  if p_entity_type not in ('student', 'teacher', 'classroom', 'schedule', 'lead') then
    raise exception 'Unsupported activity entity type.';
  end if;

  insert into public.admin_activity_logs (
    actor_teacher_id,
    action_type,
    entity_type,
    entity_id,
    entity_label,
    details
  ) values (
    p_actor_teacher_id,
    trim(p_action_type),
    p_entity_type,
    p_entity_id,
    trim(p_entity_label),
    coalesce(p_details, '{}'::jsonb)
  )
  returning id into v_log_id;

  return v_log_id;
end;
$function$;
