-- Marketing > Forms: forms the admin builds, and what people submit.
--
-- forms.fields holds the field list the builder produces (see
-- src/lib/forms.ts). form_submissions.answers is a snapshot array of
-- { id, label, value }, so renaming or deleting a field later never changes
-- what was already submitted.
--
-- Visitors are not logged in, so they never touch these tables directly:
-- get_public_form() and submit_form() are the only anon entry points. Both are
-- security definer; submit_form validates every answer against the saved form
-- on the server and, when the form asks for it, creates the Lead.

create table if not exists public.forms (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 1 and 120),
  fields jsonb not null default '[]'::jsonb,
  settings jsonb not null default '{}'::jsonb,
  is_published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  updated_by_teacher_id bigint references public.teachers (id) on delete set null
);

create table if not exists public.form_submissions (
  id bigint generated by default as identity primary key,
  form_id uuid not null references public.forms (id) on delete cascade,
  answers jsonb not null default '[]'::jsonb,
  lead_id bigint references public.leads (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_form_submissions_form_id
on public.form_submissions (form_id, created_at desc);

create index if not exists idx_form_submissions_lead_id
on public.form_submissions (lead_id);

create or replace function public.forms_touch()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.updated_at := timezone('utc', now());
  new.updated_by_teacher_id := public.current_teacher_id();
  return new;
end;
$$;

revoke all on function public.forms_touch() from public, anon, authenticated;

drop trigger if exists forms_touch on public.forms;
create trigger forms_touch
before insert or update on public.forms
for each row execute function public.forms_touch();

alter table public.forms enable row level security;
alter table public.form_submissions enable row level security;

create policy "forms_select_admin" on public.forms
for select to authenticated using (public.is_admin());

create policy "forms_insert_admin" on public.forms
for insert to authenticated with check (public.is_admin());

create policy "forms_update_admin" on public.forms
for update to authenticated using (public.is_admin()) with check (public.is_admin());

create policy "forms_delete_admin" on public.forms
for delete to authenticated using (public.is_admin());

create policy "form_submissions_select_admin" on public.form_submissions
for select to authenticated using (public.is_admin());

create policy "form_submissions_delete_admin" on public.form_submissions
for delete to authenticated using (public.is_admin());

revoke all on public.forms, public.form_submissions from anon;
grant select, insert, update, delete on public.forms to authenticated;
grant select, delete on public.form_submissions to authenticated;

-- What the public page needs to draw a form. Unpublished forms look missing.
create or replace function public.get_public_form(p_form_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id', f.id,
    'name', f.name,
    'fields', f.fields,
    'settings', f.settings
  )
  from public.forms f
  where f.id = p_form_id
    and f.is_published;
$$;

revoke all on function public.get_public_form(uuid) from public;
grant execute on function public.get_public_form(uuid) to anon, authenticated;

-- Stores one submission. p_answers is an object keyed by field id. Anything
-- that does not match the saved form is rejected or dropped here, so a forged
-- request cannot write more than the form asks for.
create or replace function public.submit_form(
  p_form_id uuid,
  p_answers jsonb,
  p_honeypot text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_form public.forms;
  v_field jsonb;
  v_type text;
  v_label text;
  v_map text;
  v_raw jsonb;
  v_value text;
  v_item text;
  v_max_len int;
  v_options jsonb;
  v_clean jsonb := '[]'::jsonb;
  v_parent_name text;
  v_phone text;
  v_child_name text;
  v_child_age int;
  v_notes text[] := '{}';
  v_children jsonb := '[]'::jsonb;
  v_source_label text;
  v_source_id bigint;
  v_lead_id bigint;
  v_submission_id bigint;
begin
  -- Bots fill hidden fields; pretend it worked and keep nothing.
  if coalesce(btrim(p_honeypot), '') <> '' then
    return jsonb_build_object('ok', true);
  end if;

  select * into v_form from public.forms where id = p_form_id and is_published;
  if not found then
    raise exception 'This form is not available.';
  end if;

  if p_answers is null or jsonb_typeof(p_answers) <> 'object' then
    raise exception 'Invalid submission.';
  end if;

  for v_field in select * from jsonb_array_elements(v_form.fields)
  loop
    v_type := v_field ->> 'type';
    v_label := coalesce(v_field ->> 'label', '');
    v_map := nullif(v_field ->> 'mapTo', '');
    v_raw := p_answers -> (v_field ->> 'id');
    v_options := coalesce(v_field -> 'options', '[]'::jsonb);
    v_value := null;

    if v_type = 'checkbox' then
      -- A list of picked options, stored as "A, B".
      if v_raw is not null and jsonb_typeof(v_raw) = 'array' then
        for v_item in select jsonb_array_elements_text(v_raw)
        loop
          if not (v_options ? v_item) then
            raise exception '% has an option that is not allowed.', v_label;
          end if;
          v_value := case when v_value is null then v_item else v_value || ', ' || v_item end;
        end loop;
      end if;
    elsif v_raw is not null and jsonb_typeof(v_raw) = 'string' then
      v_value := btrim(v_raw #>> '{}');
    end if;

    if v_value = '' then
      v_value := null;
    end if;

    if v_value is null then
      if coalesce((v_field ->> 'required')::boolean, false) then
        raise exception '% is required.', v_label;
      end if;
      continue;
    end if;

    v_max_len := case when v_type = 'long_text' then 4000 else 500 end;
    if char_length(v_value) > v_max_len then
      raise exception '% is too long.', v_label;
    end if;

    if v_type in ('dropdown', 'radio') and not (v_options ? v_value) then
      raise exception '% has an option that is not allowed.', v_label;
    end if;

    if v_type = 'email' and v_value !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
      raise exception '% is not a valid email.', v_label;
    end if;

    if v_type = 'phone' and v_value !~ '^[0-9+()\-\s.]{6,30}$' then
      raise exception '% is not a valid phone number.', v_label;
    end if;

    if v_type = 'number' and v_value !~ '^-?[0-9]+(\.[0-9]+)?$' then
      raise exception '% must be a number.', v_label;
    end if;

    if v_type = 'date' and v_value !~ '^\d{4}-\d{2}-\d{2}$' then
      raise exception '% is not a valid date.', v_label;
    end if;

    v_clean := v_clean || jsonb_build_array(
      jsonb_build_object('id', v_field ->> 'id', 'label', v_label, 'value', v_value)
    );

    if v_map = 'parent_name' then
      v_parent_name := v_value;
    elsif v_map = 'phone' then
      v_phone := v_value;
    elsif v_map = 'child_name' then
      v_child_name := v_value;
    elsif v_map = 'child_age' then
      if v_value ~ '^[0-9]{1,2}$' then
        v_child_age := v_value::int;
      end if;
    elsif v_map = 'notes' then
      v_notes := v_notes || (v_label || ': ' || v_value);
    end if;
  end loop;

  if jsonb_array_length(v_clean) = 0 then
    raise exception 'The form is empty.';
  end if;

  if coalesce((v_form.settings ->> 'createLead')::boolean, true) then
    -- A lead needs at least a name or a phone to be worth following up.
    if v_parent_name is null and v_phone is null and v_child_name is null then
      -- Nothing mapped: keep every answer in the notes instead.
      select array_agg((a ->> 'label') || ': ' || (a ->> 'value'))
      into v_notes
      from jsonb_array_elements(v_clean) a;
    end if;

    if v_child_age is not null and v_child_age between 1 and 99 then
      v_children := jsonb_build_array(
        jsonb_build_object(
          'name', coalesce(v_child_name, 'Child'),
          'age', v_child_age,
          'phone', null
        )
      );
    end if;

    v_source_label := left('Form: ' || btrim(v_form.name), 60);
    insert into public.lead_options (kind, label)
    values ('source', v_source_label)
    on conflict do nothing;

    select id into v_source_id
    from public.lead_options
    where kind = 'source'
      and lower(btrim(label)) = lower(btrim(v_source_label));

    insert into public.leads (full_name, phone, source_id, status, children, notes)
    values (
      v_parent_name,
      v_phone,
      v_source_id,
      'new',
      v_children,
      nullif(array_to_string(v_notes, E'\n'), '')
    )
    returning id into v_lead_id;
  end if;

  insert into public.form_submissions (form_id, answers, lead_id)
  values (p_form_id, v_clean, v_lead_id)
  returning id into v_submission_id;

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.submit_form(uuid, jsonb, text) from public;
grant execute on function public.submit_form(uuid, jsonb, text) to anon, authenticated;
