-- Phase 2 schema for the teaching admin system
-- Recommended: run this in Supabase SQL Editor
-- Important: do not store plain-text passwords.
-- Keep password handling in Supabase Auth whenever possible.

create table if not exists public.teachers (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users (id) on delete set null,
  username text not null unique,
  password_hash text,
  full_name text not null,
  email text unique,
  phone text,
  role text not null default 'teacher' check (role in ('admin', 'teacher')),
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.students (
  id bigint generated by default as identity primary key,
  teacher_id bigint references public.teachers (id) on delete set null,
  full_name text not null,
  remaining_hours integer not null default 0,
  lesson_expiry_date date not null,
  account_fee_expiry_date date not null,
  mirai_club_expiry_date date not null,
  notes text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists set_teachers_updated_at on public.teachers;
create trigger set_teachers_updated_at
before update on public.teachers
for each row
execute function public.set_current_timestamp_updated_at();

drop trigger if exists set_students_updated_at on public.students;
create trigger set_students_updated_at
before update on public.students
for each row
execute function public.set_current_timestamp_updated_at();

alter table public.teachers enable row level security;
alter table public.students enable row level security;

drop policy if exists "temp_dev_students_select" on public.students;
create policy "temp_dev_students_select"
on public.students
for select
to anon, authenticated
using (true);

drop policy if exists "temp_dev_students_update" on public.students;
create policy "temp_dev_students_update"
on public.students
for update
to anon, authenticated
using (true)
with check (true);

insert into public.teachers (
  username,
  password_hash,
  full_name,
  email,
  role
) values (
  'admin_demo',
  '$2b$12$replace_with_real_hash_before_production',
  'Admin Demo',
  'admin@example.com',
  'admin'
)
on conflict (username) do nothing;

insert into public.students (
  teacher_id,
  full_name,
  remaining_hours,
  lesson_expiry_date,
  account_fee_expiry_date,
  mirai_club_expiry_date,
  notes
)
select
  teacher.id,
  seed.full_name,
  seed.remaining_hours,
  seed.lesson_expiry_date,
  seed.account_fee_expiry_date,
  seed.mirai_club_expiry_date,
  seed.notes
from (
  values
    ('Olivia Tan', 12, date '2026-09-15', date '2026-08-22', date '2026-08-28', 'Healthy sample row'),
    ('Ethan Lim', 2, date '2026-08-10', date '2026-09-01', date '2026-08-18', 'Low hours sample row'),
    ('Chloe Wong', 6, date '2026-06-20', date '2026-09-10', date '2026-09-15', 'Expired lesson sample row'),
    ('Ryan Koh', -1, date '2026-06-15', date '2026-07-05', date '2026-07-03', 'Negative hours are allowed by business rule')
) as seed (
  full_name,
  remaining_hours,
  lesson_expiry_date,
  account_fee_expiry_date,
  mirai_club_expiry_date,
  notes
)
cross join lateral (
  select id
  from public.teachers
  where username = 'admin_demo'
  limit 1
) as teacher
where not exists (
  select 1
  from public.students existing
  where existing.full_name = seed.full_name
);
