-- Trial slots: an (initially empty) weekly schedule on a trial classroom is a
-- slot the team can offer for trials. Who is coming on a given day lives in
-- trial_bookings, one row per child per date, so the calendar can show a slot
-- as "available" (nobody booked) or "booked" (one or more children) per day.
-- Multiple children may book the same slot.

create table if not exists public.trial_bookings (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules (id) on delete cascade,
  booking_date date not null,
  lead_id bigint references public.leads (id) on delete set null,
  child_name text not null,
  child_age integer,
  phone text,
  notes text,
  created_by bigint references public.teachers (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_trial_bookings_schedule_date
on public.trial_bookings (schedule_id, booking_date);

create index if not exists idx_trial_bookings_lead_id
on public.trial_bookings (lead_id);

alter table public.trial_bookings enable row level security;

-- Admins see every booking; a teacher only sees bookings on their own slots.
-- Writes go through the RPCs below only (no insert/update/delete policy).
create policy "trial_bookings_select_scoped"
on public.trial_bookings
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.schedules s
    where s.id = trial_bookings.schedule_id
      and s.teacher_id = public.current_teacher_id()
  )
);

create or replace function public.book_trial_slot(
  p_schedule_id bigint,
  p_booking_date date,
  p_child_name text,
  p_child_age integer default null,
  p_phone text default null,
  p_lead_id bigint default null,
  p_notes text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_schedule public.schedules%rowtype;
  v_classroom public.classrooms%rowtype;
  v_lead public.leads%rowtype;
  v_child_name text := trim(coalesce(p_child_name, ''));
  v_phone text := nullif(trim(coalesce(p_phone, '')), '');
  v_notes text := nullif(trim(coalesce(p_notes, '')), '');
  v_lead_id bigint;
  v_children jsonb;
  v_booking_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Only admins can book a trial class.';
  end if;

  if v_child_name = '' then
    raise exception 'Child name is required.';
  end if;

  if p_child_age is not null and (p_child_age < 1 or p_child_age > 25) then
    raise exception 'Child age must be between 1 and 25.';
  end if;

  -- FOR SHARE serialises with cancel_schedule_occurrence (FOR UPDATE), so a
  -- day cannot be cancelled and booked at the same moment.
  select * into v_schedule
  from public.schedules
  where id = p_schedule_id
  for share;

  if not found then
    raise exception 'Schedule not found.';
  end if;

  if v_schedule.status <> 'active' or v_schedule.event_type <> 'regular' then
    raise exception 'This is not an active weekly trial slot.';
  end if;

  select * into v_classroom
  from public.classrooms
  where id = v_schedule.classroom_id;

  if not found or v_classroom.category <> 'trial' or v_classroom.status <> 'active' then
    raise exception 'This schedule is not an active trial classroom slot.';
  end if;

  if p_booking_date is null
    or extract(dow from p_booking_date)::int <> v_schedule.day_of_week
    or p_booking_date < v_schedule.start_recur
    or (v_schedule.end_recur is not null and p_booking_date > v_schedule.end_recur) then
    raise exception 'This trial slot does not run on that date.';
  end if;

  if exists (
    select 1 from public.schedule_exceptions
    where schedule_id = p_schedule_id
      and exception_date = p_booking_date
  ) then
    raise exception 'This trial slot is cancelled on that date.';
  end if;

  if exists (
    select 1 from public.trial_bookings
    where schedule_id = p_schedule_id
      and booking_date = p_booking_date
      and lower(child_name) = lower(v_child_name)
      and coalesce(phone, '') = coalesce(v_phone, '')
  ) then
    raise exception 'This child is already booked for that trial slot.';
  end if;

  if p_lead_id is not null then
    select * into v_lead
    from public.leads
    where id = p_lead_id
    for update;

    if not found then
      raise exception 'Lead not found.';
    end if;

    v_lead_id := v_lead.id;
    v_children := v_lead.children;

    -- Attach the child to the lead when it is not on it yet (a lead holds at
    -- most 3 children, and a child needs an age to be stored on a lead).
    if p_child_age is not null
      and jsonb_array_length(v_children) < 3
      and not exists (
        select 1 from jsonb_array_elements(v_children) child
        where lower(trim(coalesce(child ->> 'name', ''))) = lower(v_child_name)
      ) then
      v_children := v_children || jsonb_build_array(
        jsonb_build_object('name', v_child_name, 'age', p_child_age, 'phone', v_phone)
      );
    end if;

    update public.leads
    set
      children = v_children,
      phone = coalesce(phone, v_phone),
      status = case when status in ('new', 'contacted') then 'trial_scheduled' else status end
    where id = v_lead.id;
  else
    -- Not in Leads yet: booking creates the lead so the pipeline stays in sync.
    if p_child_age is null then
      raise exception 'Child age is required to add a new lead.';
    end if;

    insert into public.leads (full_name, phone, source, status, children, notes, added_date)
    values (
      null,
      v_phone,
      'other',
      'trial_scheduled',
      jsonb_build_array(
        jsonb_build_object('name', v_child_name, 'age', p_child_age, 'phone', v_phone)
      ),
      v_notes,
      (timezone('Asia/Kuala_Lumpur', now()))::date
    )
    returning id into v_lead_id;

    perform public.record_admin_activity(
      'lead_created',
      'lead',
      v_lead_id,
      v_child_name,
      jsonb_build_object('source', 'trial_booking')
    );
  end if;

  insert into public.trial_bookings (
    schedule_id, booking_date, lead_id, child_name, child_age, phone, notes, created_by
  )
  values (
    p_schedule_id,
    p_booking_date,
    v_lead_id,
    v_child_name,
    p_child_age,
    v_phone,
    v_notes,
    public.current_teacher_id()
  )
  returning id into v_booking_id;

  perform public.record_admin_activity(
    'trial_booked',
    'schedule',
    p_schedule_id,
    v_classroom.name,
    jsonb_build_object(
      'booking_date', p_booking_date,
      'child_name', v_child_name,
      'lead_id', v_lead_id
    )
  );

  return v_booking_id;
end;
$$;

create or replace function public.cancel_trial_booking(
  p_booking_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_booking public.trial_bookings%rowtype;
  v_label text;
begin
  if not public.is_admin() then
    raise exception 'Only admins can cancel a trial booking.';
  end if;

  select * into v_booking
  from public.trial_bookings
  where id = p_booking_id
  for update;

  if not found then
    raise exception 'Trial booking not found.';
  end if;

  select c.name into v_label
  from public.schedules s
  left join public.classrooms c on c.id = s.classroom_id
  where s.id = v_booking.schedule_id;

  delete from public.trial_bookings where id = p_booking_id;

  perform public.record_admin_activity(
    'trial_booking_cancelled',
    'schedule',
    v_booking.schedule_id,
    coalesce(v_label, 'Trial slot'),
    jsonb_build_object(
      'booking_date', v_booking.booking_date,
      'child_name', v_booking.child_name,
      'lead_id', v_booking.lead_id
    )
  );
end;
$$;

revoke all on function public.book_trial_slot(bigint, date, text, integer, text, bigint, text)
  from public, anon;
revoke all on function public.cancel_trial_booking(bigint) from public, anon;
grant execute on function public.book_trial_slot(bigint, date, text, integer, text, bigint, text)
  to authenticated;
grant execute on function public.cancel_trial_booking(bigint) to authenticated;

-- A day that already has trial bookings cannot be cancelled until the
-- bookings are cancelled or moved. (Same function as in
-- 20260921100000_schedule_occurrence_hardening.sql plus that one check.)
create or replace function public.cancel_schedule_occurrence(
  p_schedule_id bigint,
  p_occurrence_date date,
  p_reason text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_schedule public.schedules%rowtype;
  v_exception_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Only admins can cancel a class occurrence.';
  end if;

  select * into v_schedule
  from public.schedules
  where id = p_schedule_id
  for update;

  if not found then
    raise exception 'Schedule not found.';
  end if;

  if v_schedule.event_type <> 'regular' then
    raise exception 'Only regular weekly classes can skip a single day. Cancel the replacement class instead.';
  end if;

  if v_schedule.status <> 'active' then
    raise exception 'This schedule is already cancelled.';
  end if;

  if extract(dow from p_occurrence_date)::int <> v_schedule.day_of_week
    or p_occurrence_date < v_schedule.start_recur
    or (v_schedule.end_recur is not null and p_occurrence_date > v_schedule.end_recur) then
    raise exception 'This schedule does not run on that date.';
  end if;

  if exists (
    select 1 from public.lesson_logs
    where schedule_id = p_schedule_id
      and lesson_date = p_occurrence_date
  ) then
    raise exception 'Attendance was already submitted for this day, so it cannot be cancelled.';
  end if;

  if exists (
    select 1 from public.trial_bookings
    where schedule_id = p_schedule_id
      and booking_date = p_occurrence_date
  ) then
    raise exception 'This day has trial bookings. Cancel or move them before cancelling the day.';
  end if;

  insert into public.schedule_exceptions (schedule_id, exception_date, reason, created_by)
  values (
    p_schedule_id,
    p_occurrence_date,
    nullif(trim(coalesce(p_reason, '')), ''),
    public.current_teacher_id()
  )
  on conflict (schedule_id, exception_date) do nothing
  returning id into v_exception_id;

  if v_exception_id is not null then
    perform public.record_admin_activity(
      'schedule_occurrence_cancelled',
      'schedule',
      p_schedule_id,
      v_schedule.title,
      jsonb_build_object('occurrence_date', p_occurrence_date)
    );
  end if;

  return v_exception_id;
end;
$$;
