-- Cancel a single day of a recurring (regular) class without cancelling the
-- whole weekly series. Each row is one skipped occurrence; the calendar
-- feeds these dates to FullCalendar as rrule `exdate`s.

create table if not exists public.schedule_exceptions (
  id bigint generated by default as identity primary key,
  schedule_id bigint not null references public.schedules (id) on delete cascade,
  exception_date date not null,
  reason text,
  created_by bigint references public.teachers (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (schedule_id, exception_date)
);

create index if not exists idx_schedule_exceptions_schedule_id
on public.schedule_exceptions (schedule_id);

alter table public.schedule_exceptions enable row level security;

-- Same visibility as schedules: admins see all, a teacher only sees the
-- exceptions of their own schedules. Writes go through the RPCs below only
-- (no insert/update/delete policy on purpose).
create policy "schedule_exceptions_select_scoped"
on public.schedule_exceptions
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.schedules s
    where s.id = schedule_exceptions.schedule_id
      and s.teacher_id = public.current_teacher_id()
  )
);

create or replace function public.cancel_schedule_occurrence(
  p_schedule_id bigint,
  p_occurrence_date date,
  p_reason text default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_schedule public.schedules%rowtype;
  v_exception_id bigint;
begin
  if not public.is_admin() then
    raise exception 'Only admins can cancel a class occurrence.';
  end if;

  select * into v_schedule from public.schedules where id = p_schedule_id;

  if not found then
    raise exception 'Schedule not found.';
  end if;

  if v_schedule.event_type <> 'regular' then
    raise exception 'Only regular weekly classes can skip a single day. Cancel the replacement class instead.';
  end if;

  if v_schedule.status <> 'active' then
    raise exception 'This schedule is already cancelled.';
  end if;

  if extract(dow from p_occurrence_date)::int <> v_schedule.day_of_week
    or p_occurrence_date < v_schedule.start_recur
    or (v_schedule.end_recur is not null and p_occurrence_date > v_schedule.end_recur) then
    raise exception 'This schedule does not run on that date.';
  end if;

  if exists (
    select 1 from public.lesson_logs
    where schedule_id = p_schedule_id
      and lesson_date = p_occurrence_date
  ) then
    raise exception 'Attendance was already submitted for this day, so it cannot be cancelled.';
  end if;

  insert into public.schedule_exceptions (schedule_id, exception_date, reason, created_by)
  values (
    p_schedule_id,
    p_occurrence_date,
    nullif(trim(coalesce(p_reason, '')), ''),
    public.current_teacher_id()
  )
  on conflict (schedule_id, exception_date) do nothing
  returning id into v_exception_id;

  if v_exception_id is not null then
    perform public.record_admin_activity(
      'schedule_occurrence_cancelled',
      'schedule',
      p_schedule_id,
      v_schedule.title,
      jsonb_build_object('occurrence_date', p_occurrence_date)
    );
  end if;

  return v_exception_id;
end;
$$;

create or replace function public.restore_schedule_occurrence(
  p_schedule_id bigint,
  p_occurrence_date date
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_title text;
  v_deleted integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can restore a class occurrence.';
  end if;

  select title into v_title from public.schedules where id = p_schedule_id;

  if not found then
    raise exception 'Schedule not found.';
  end if;

  delete from public.schedule_exceptions
  where schedule_id = p_schedule_id
    and exception_date = p_occurrence_date;

  get diagnostics v_deleted = row_count;

  if v_deleted > 0 then
    perform public.record_admin_activity(
      'schedule_occurrence_restored',
      'schedule',
      p_schedule_id,
      v_title,
      jsonb_build_object('occurrence_date', p_occurrence_date)
    );
  end if;
end;
$$;

revoke all on function public.cancel_schedule_occurrence(bigint, date, text) from public, anon;
revoke all on function public.restore_schedule_occurrence(bigint, date) from public, anon;
grant execute on function public.cancel_schedule_occurrence(bigint, date, text) to authenticated;
grant execute on function public.restore_schedule_occurrence(bigint, date) to authenticated;

-- Attendance must never be recorded for a day that was cancelled. A trigger
-- (rather than redefining submit_lesson_attendance) keeps this enforced for
-- every insert path without touching that large function.
create or replace function public.block_lesson_log_on_cancelled_occurrence()
returns trigger
language plpgsql
as $$
begin
  if exists (
    select 1 from public.schedule_exceptions
    where schedule_id = new.schedule_id
      and exception_date = new.lesson_date
  ) then
    raise exception 'This class was cancelled for that day, so attendance cannot be submitted.';
  end if;

  return new;
end;
$$;

drop trigger if exists block_lesson_log_on_cancelled_occurrence on public.lesson_logs;
create trigger block_lesson_log_on_cancelled_occurrence
before insert on public.lesson_logs
for each row
execute function public.block_lesson_log_on_cancelled_occurrence();
