-- Marketing upgrades for forms: spam protection, where visitors came from,
-- closing a form (deadline or a limit on places), and email alerts.
--
-- * Spam: submit_form and save_form_progress count calls per connection and
--   per form. A connection that sends more than 20 finished forms in 10 minutes
--   (or a form that gets more than 200 in 10 minutes) is turned away. Saving
--   progress has its own, wider limit. When the connection's address is not
--   known only the per-form limit applies.
-- * Tracking: submit_form takes an optional object { source, medium, campaign,
--   content, referrer } (from ?utm_source=... in the link) and keeps it on the
--   submission.
-- * Closing: forms.settings.closesAt (an ISO time) and maxSubmissions (a number
--   of finished submissions) close a form; submit_form refuses after that and
--   the public page shows closedReason.
-- * Alerts: forms.settings.notifyEmails stays private (the public page only
--   learns that alerts are on); form_submissions.notified_at lets the
--   notify-form-submission function send each submission's email once.

alter table public.form_submissions
  add column if not exists tracking jsonb,
  add column if not exists notified_at timestamptz;

-- Calls kept for rate limiting. Nobody but the functions below touches it.
create table if not exists public.form_rate_hits (
  id bigint generated by default as identity primary key,
  bucket text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_form_rate_hits_bucket
on public.form_rate_hits (bucket, created_at desc);

alter table public.form_rate_hits enable row level security;
revoke all on public.form_rate_hits from anon, authenticated;

-- The caller's address, as the gateway reports it.
create or replace function public.form_client_key()
returns text
language sql
stable
as $$
  select nullif(btrim(split_part(coalesce(
    nullif(h ->> 'cf-connecting-ip', ''),
    nullif(h ->> 'x-real-ip', ''),
    nullif(h ->> 'x-forwarded-for', ''),
    ''
  ), ',', 1)), '')
  from (
    select case
      when coalesce(current_setting('request.headers', true), '') = '' then '{}'::jsonb
      else current_setting('request.headers', true)::jsonb
    end as h
  ) s;
$$;

revoke all on function public.form_client_key() from public, anon, authenticated;

-- Raises when this connection (or the whole form) has made too many calls of
-- this kind in the last 10 minutes.
create or replace function public.form_rate_check(
  p_kind text,
  p_form_id uuid,
  p_ip_limit int,
  p_flood_limit int
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ip text := public.form_client_key();
  v_since timestamptz := now() - interval '10 minutes';
begin
  if v_ip is not null and (
    select count(*) from public.form_rate_hits
    where bucket = p_kind || ':ip:' || p_form_id::text || ':' || md5(v_ip)
      and created_at > v_since
  ) >= p_ip_limit then
    raise exception 'Too many tries from your connection. Please wait a few minutes and try again.';
  end if;

  if (
    select count(*) from public.form_rate_hits
    where bucket = p_kind || ':all:' || p_form_id::text
      and created_at > v_since
  ) >= p_flood_limit then
    raise exception 'This form is getting a lot of traffic. Please try again in a few minutes.';
  end if;
end;
$$;

create or replace function public.form_rate_record(p_kind text, p_form_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_ip text := public.form_client_key();
begin
  insert into public.form_rate_hits (bucket)
  values (p_kind || ':all:' || p_form_id::text);

  if v_ip is not null then
    insert into public.form_rate_hits (bucket)
    values (p_kind || ':ip:' || p_form_id::text || ':' || md5(v_ip));
  end if;

  -- Old calls are of no use; clear them now and then.
  if random() < 0.02 then
    delete from public.form_rate_hits where created_at < now() - interval '1 day';
  end if;
end;
$$;

revoke all on function public.form_rate_check(text, uuid, int, int) from public, anon, authenticated;
revoke all on function public.form_rate_record(text, uuid) from public, anon, authenticated;

-- Only the few known keys are kept, as short plain text.
create or replace function public.clean_form_tracking(p_tracking jsonb)
returns jsonb
language sql
immutable
as $$
  select nullif(jsonb_object_agg(t.k, t.v), '{}'::jsonb)
  from (
    select k, left(regexp_replace(btrim(p_tracking ->> k), '[[:cntrl:]]', '', 'g'), 100) as v
    from unnest(array['source', 'medium', 'campaign', 'content', 'referrer']) as k
    where p_tracking is not null
      and jsonb_typeof(p_tracking) = 'object'
      and jsonb_typeof(p_tracking -> k) = 'string'
  ) t
  where t.v <> '';
$$;

revoke all on function public.clean_form_tracking(jsonb) from public, anon, authenticated;

-- Why a form is not taking answers right now: 'deadline', 'full', or null.
create or replace function public.form_closed_reason(p_form public.forms)
returns text
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  v_text text;
  v_closes timestamptz;
  v_max int;
begin
  v_text := p_form.settings ->> 'closesAt';
  if v_text ~ '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}' then
    begin
      v_closes := v_text::timestamptz;
    exception when others then
      v_closes := null;
    end;
  end if;
  if v_closes is not null and now() >= v_closes then
    return 'deadline';
  end if;

  v_text := p_form.settings ->> 'maxSubmissions';
  if v_text ~ '^[0-9]{1,6}$' then
    v_max := v_text::int;
  end if;
  if v_max is not null and v_max > 0 and (
    select count(*) from public.form_submissions s
    where s.form_id = p_form.id and s.status = 'completed'
  ) >= v_max then
    return 'full';
  end if;

  return null;
end;
$$;

revoke all on function public.form_closed_reason(public.forms) from public, anon, authenticated;

-- What the public page may know about a form. The people to email stay
-- private: the page only learns whether alerts are on.
create or replace function public.get_public_form_by_key(p_form_key text)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id', f.id,
    'name', f.name,
    'fields', f.fields,
    'settings', f.settings - 'notifyEmails',
    'notify', (
      case when jsonb_typeof(f.settings -> 'notifyEmails') = 'array'
        then jsonb_array_length(f.settings -> 'notifyEmails') > 0
        else false
      end
    ),
    'closedReason', public.form_closed_reason(f)
  )
  from public.forms f
  where f.is_published
    and (
      f.slug = lower(btrim(p_form_key))
      or f.id::text = lower(btrim(p_form_key))
    )
  limit 1;
$$;

revoke all on function public.get_public_form_by_key(text) from public;
grant execute on function public.get_public_form_by_key(text) to anon, authenticated;

create or replace function public.get_public_form(p_form_id uuid)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'id', f.id,
    'name', f.name,
    'fields', f.fields,
    'settings', f.settings - 'notifyEmails',
    'notify', (
      case when jsonb_typeof(f.settings -> 'notifyEmails') = 'array'
        then jsonb_array_length(f.settings -> 'notifyEmails') > 0
        else false
      end
    ),
    'closedReason', public.form_closed_reason(f)
  )
  from public.forms f
  where f.id = p_form_id
    and f.is_published;
$$;

revoke all on function public.get_public_form(uuid) from public;
grant execute on function public.get_public_form(uuid) to anon, authenticated;

-- One signature only: the new optional argument has a default, so callers
-- that do not send it keep working.
drop function if exists public.submit_form(uuid, jsonb, text, uuid);

create or replace function public.submit_form(
  p_form_id uuid,
  p_answers jsonb,
  p_honeypot text default '',
  p_token uuid default null,
  p_tracking jsonb default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_form public.forms;
  v_field jsonb;
  v_type text;
  v_label text;
  v_map text;
  v_key text;
  v_raw jsonb;
  v_value text;
  v_item text;
  v_options jsonb;
  v_max_len int;
  v_clean jsonb := '[]'::jsonb;
  v_max_children int := 1;
  v_n int;
  v_has_block boolean;
  v_parent_name text;
  v_phone text;
  v_notes text[] := '{}';
  v_child_name text[] := array[null, null, null]::text[];
  v_child_age int[] := array[null, null, null]::int[];
  v_child_phone text[] := array[null, null, null]::text[];
  v_children jsonb := '[]'::jsonb;
  v_source_label text;
  v_source_id bigint;
  v_lead_id bigint;
  v_existing boolean := false;
  v_age_ok boolean;
  v_pages jsonb;
  v_visited text[];
  v_first_page text;
  v_field_page text;
  v_completed boolean;
  v_closed text;
  v_tracking jsonb;
begin
  -- Bots fill hidden fields; pretend it worked and keep nothing.
  if coalesce(btrim(p_honeypot), '') <> '' then
    return jsonb_build_object('ok', true);
  end if;

  select * into v_form from public.forms where id = p_form_id and is_published;
  if not found then
    raise exception 'This form is not available.';
  end if;

  if p_answers is null or jsonb_typeof(p_answers) <> 'object' then
    raise exception 'Invalid submission.';
  end if;

  -- Sending the same finished form twice (a double click) must not make a
  -- second lead.
  if p_token is not null then
    select true into v_completed
    from public.form_submissions
    where form_id = p_form_id and session_token = p_token and status = 'completed';
    if v_completed then
      return jsonb_build_object('ok', true);
    end if;
  end if;

  perform pg_advisory_xact_lock(hashtext(p_form_id::text));

  v_closed := public.form_closed_reason(v_form);
  if v_closed is not null then
    raise exception 'This form is no longer accepting responses.';
  end if;

  perform public.form_rate_check('submit', p_form_id, 20, 200);

  v_tracking := public.clean_form_tracking(p_tracking);

  if coalesce((v_form.settings ->> 'allowMoreChildren')::boolean, false) then
    v_max_children := 3;
  end if;

  v_pages := coalesce(v_form.settings -> 'pages', '[]'::jsonb);
  v_visited := public.form_visited_pages(v_pages, p_answers);
  v_first_page := v_pages -> 0 ->> 'id';

  for v_n in 1..v_max_children
  loop
    -- An extra child's block only counts when something was filled in.
    v_has_block := (v_n = 1);
    if v_n > 1 then
      for v_field in select * from jsonb_array_elements(v_form.fields)
      loop
        if (v_field ->> 'mapTo') in ('child_name', 'child_age', 'child_phone')
           and coalesce(btrim(p_answers ->> ((v_field ->> 'id') || '#' || v_n)), '') <> '' then
          v_has_block := true;
        end if;
      end loop;
    end if;

    if not v_has_block then
      continue;
    end if;

    for v_field in select * from jsonb_array_elements(v_form.fields)
    loop
      v_type := v_field ->> 'type';
      v_map := nullif(v_field ->> 'mapTo', '');

      -- A question on a page the person skipped is not asked or stored. A
      -- field on a page that does not exist counts as being on the first one.
      if v_visited is not null then
        v_field_page := coalesce(nullif(v_field ->> 'pageId', ''), v_first_page);
        if not exists (
          select 1 from jsonb_array_elements(v_pages) p where p ->> 'id' = v_field_page
        ) then
          v_field_page := v_first_page;
        end if;
        if not (v_field_page = any(v_visited)) then
          continue;
        end if;
      end if;

      if v_n > 1 and coalesce(v_map, '') not in ('child_name', 'child_age', 'child_phone') then
        continue;
      end if;

      v_label := coalesce(v_field ->> 'label', '');
      v_key := (v_field ->> 'id') || case when v_n > 1 then '#' || v_n else '' end;
      v_raw := p_answers -> v_key;
      v_options := coalesce(v_field -> 'options', '[]'::jsonb);
      v_value := null;

      if v_n > 1 then
        v_label := v_label || ' (child ' || v_n || ')';
      end if;

      if v_type = 'checkbox' then
        -- A list of picked options, stored as "A, B".
        if v_raw is not null and jsonb_typeof(v_raw) = 'array' then
          for v_item in select jsonb_array_elements_text(v_raw)
          loop
            if not (v_options ? v_item) then
              raise exception '% has an option that is not allowed.', v_label;
            end if;
            v_value := case when v_value is null then v_item else v_value || ', ' || v_item end;
          end loop;
        end if;
      elsif v_raw is not null and jsonb_typeof(v_raw) = 'string' then
        v_value := btrim(v_raw #>> '{}');
      end if;

      if v_value = '' then
        v_value := null;
      end if;

      if v_value is null then
        if coalesce((v_field ->> 'required')::boolean, false) then
          raise exception '% is required.', v_label;
        end if;
        continue;
      end if;

      v_max_len := case when v_type = 'long_text' then 4000 else 500 end;
      if char_length(v_value) > v_max_len then
        raise exception '% is too long.', v_label;
      end if;

      if v_type in ('dropdown', 'radio') and not (v_options ? v_value) then
        raise exception '% has an option that is not allowed.', v_label;
      end if;

      if v_type = 'email' and v_value !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then
        raise exception '% is not a valid email.', v_label;
      end if;

      if v_type = 'phone' and v_value !~ '^[0-9+()\-\s.]{6,30}$' then
        raise exception '% is not a valid phone number.', v_label;
      end if;

      if v_type = 'number' and v_value !~ '^-?[0-9]+(\.[0-9]+)?$' then
        raise exception '% must be a number.', v_label;
      end if;

      if v_map = 'child_age' then
        v_age_ok := case when v_value ~ '^[0-9]{1,2}$' then v_value::int >= 1 else false end;
        if not v_age_ok then
          raise exception '% must be a whole age from 1 to 99.', v_label;
        end if;
      end if;

      if v_type = 'date' and v_value !~ '^\d{4}-\d{2}-\d{2}$' then
        raise exception '% is not a valid date.', v_label;
      end if;

      v_clean := v_clean || jsonb_build_array(
        jsonb_build_object('id', v_key, 'label', v_label, 'value', v_value)
      );

      if v_map = 'parent_name' then
        v_parent_name := v_value;
      elsif v_map = 'phone' then
        v_phone := v_value;
      elsif v_map = 'child_name' then
        v_child_name[v_n] := v_value;
      elsif v_map = 'child_age' then
        v_child_age[v_n] := v_value::int;
      elsif v_map = 'child_phone' then
        v_child_phone[v_n] := v_value;
      elsif v_map = 'notes' then
        v_notes := v_notes || (v_label || ': ' || v_value);
      end if;
    end loop;
  end loop;

  if jsonb_array_length(v_clean) = 0 then
    raise exception 'The form is empty.';
  end if;

  if coalesce((v_form.settings ->> 'createLead')::boolean, true) then
    -- A lead needs at least a name or a phone to be worth following up.
    if v_parent_name is null and v_phone is null and v_child_name[1] is null then
      -- Nothing mapped: keep every answer in the notes instead.
      select array_agg((a ->> 'label') || ': ' || (a ->> 'value'))
      into v_notes
      from jsonb_array_elements(v_clean) a;
    end if;

    -- A lead stores a child only with an age; the rest goes into the notes.
    for v_n in 1..3
    loop
      if v_child_age[v_n] is not null then
        v_children := v_children || jsonb_build_array(
          jsonb_build_object(
            'name', coalesce(v_child_name[v_n], 'Child'),
            'age', v_child_age[v_n],
            'phone', v_child_phone[v_n]
          )
        );
      elsif v_child_name[v_n] is not null or v_child_phone[v_n] is not null then
        v_notes := v_notes || (
          'Child ' || v_n || ': '
          || concat_ws(' ', v_child_name[v_n], '(' || v_child_phone[v_n] || ')')
        );
      end if;
    end loop;

    -- The same phone is the same family: add to their lead, do not duplicate it.
    if v_phone is not null and public.normalize_phone(v_phone) <> '' then
      select id into v_lead_id
      from public.leads
      where public.normalize_phone(phone) = public.normalize_phone(v_phone)
      order by created_at desc
      limit 1;
    end if;

    if v_lead_id is not null then
      -- Nothing is copied into the lead: its "Form answers" in the CRM lists
      -- every submission linked to it, this one included.
      v_existing := true;
    else
      v_source_label := left('Form: ' || btrim(v_form.name), 60);
      insert into public.lead_options (kind, label)
      values ('source', v_source_label)
      on conflict do nothing;

      select id into v_source_id
      from public.lead_options
      where kind = 'source'
        and lower(btrim(label)) = lower(btrim(v_source_label));

      insert into public.leads (full_name, phone, source_id, status, children, notes)
      values (
        v_parent_name,
        v_phone,
        v_source_id,
        'new',
        v_children,
        nullif(array_to_string(v_notes, E'\n'), '')
      )
      returning id into v_lead_id;
    end if;
  end if;

  -- Finish the incomplete row saved along the way, or start a finished one.
  if p_token is not null then
    update public.form_submissions
    set answers = v_clean,
        lead_id = v_lead_id,
        lead_was_existing = v_existing,
        status = 'completed',
        tracking = v_tracking,
        created_at = timezone('utc', now())
    where form_id = p_form_id and session_token = p_token and status = 'partial';
    if found then
      perform public.form_rate_record('submit', p_form_id);
      return jsonb_build_object('ok', true);
    end if;
  end if;

  insert into public.form_submissions (form_id, answers, lead_id, lead_was_existing, session_token, tracking)
  values (p_form_id, v_clean, v_lead_id, v_existing, p_token, v_tracking);

  perform public.form_rate_record('submit', p_form_id);

  return jsonb_build_object('ok', true);
end;
$$;

revoke all on function public.submit_form(uuid, jsonb, text, uuid, jsonb) from public;
grant execute on function public.submit_form(uuid, jsonb, text, uuid, jsonb) to anon, authenticated;

-- Progress saving: nothing is kept once the form is closed, and a connection
-- that saves far too often is turned away.
create or replace function public.save_form_progress(
  p_form_id uuid,
  p_token uuid,
  p_answers jsonb,
  p_last_page int default 1
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_form public.forms;
  v_field jsonb;
  v_type text;
  v_n int;
  v_max int := 1;
  v_key text;
  v_raw jsonb;
  v_value text;
  v_label text;
  v_clean jsonb := '[]'::jsonb;
begin
  if p_token is null or p_answers is null or jsonb_typeof(p_answers) <> 'object' then
    return;
  end if;

  select * into v_form from public.forms where id = p_form_id and is_published;
  if not found then
    return;
  end if;

  if public.form_closed_reason(v_form) is not null then
    return;
  end if;

  perform public.form_rate_check('progress', p_form_id, 60, 2000);
  perform public.form_rate_record('progress', p_form_id);

  if coalesce((v_form.settings ->> 'allowMoreChildren')::boolean, false) then
    v_max := 3;
  end if;

  for v_n in 1..v_max
  loop
    for v_field in select * from jsonb_array_elements(v_form.fields)
    loop
      v_type := v_field ->> 'type';
      if v_type in ('image', 'text_block') then
        continue;
      end if;
      if v_n > 1 and coalesce(v_field ->> 'mapTo', '') not in ('child_name', 'child_age', 'child_phone') then
        continue;
      end if;

      v_key := (v_field ->> 'id') || case when v_n > 1 then '#' || v_n else '' end;
      v_raw := p_answers -> v_key;
      v_value := null;

      if v_raw is null then
        continue;
      elsif jsonb_typeof(v_raw) = 'array' then
        select string_agg(left(x, 200), ', ') into v_value
        from jsonb_array_elements_text(v_raw) x;
      elsif jsonb_typeof(v_raw) = 'string' then
        v_value := v_raw #>> '{}';
      end if;

      v_value := left(btrim(coalesce(v_value, '')), case when v_type = 'long_text' then 4000 else 500 end);
      if v_value = '' then
        continue;
      end if;

      v_label := coalesce(v_field ->> 'label', '') || case when v_n > 1 then ' (child ' || v_n || ')' else '' end;
      v_clean := v_clean || jsonb_build_array(
        jsonb_build_object('id', v_key, 'label', v_label, 'value', v_value)
      );
    end loop;
  end loop;

  if jsonb_array_length(v_clean) = 0 then
    return;
  end if;

  insert into public.form_submissions (form_id, answers, status, session_token, last_page)
  values (p_form_id, v_clean, 'partial', p_token, greatest(coalesce(p_last_page, 1), 1))
  on conflict (form_id, session_token) where session_token is not null
  do update
  set answers = excluded.answers,
      last_page = greatest(coalesce(form_submissions.last_page, 1), excluded.last_page)
  where form_submissions.status = 'partial';
end;
$$;

revoke all on function public.save_form_progress(uuid, uuid, jsonb, int) from public;
grant execute on function public.save_form_progress(uuid, uuid, jsonb, int) to anon, authenticated;
