-- Make-up plans: a missed class is often made up by adding minutes to later
-- classes (e.g. +30 min on each of the next two), agreed with the parent.
-- This records that plan. Per product decision it never touches
-- remaining_hours, and a planned session counts as made up whether or not
-- the child attends it - there is no per-session attendance tracking.
--
-- A plan covers one missed date of one classroom, for the whole class
-- (teacher leave, holiday) or one student (student leave). Plans and
-- sessions key off classroom + date rather than schedule_id, so they stay
-- correct when reassign_classroom_teacher splits a weekly series.
--
-- A session date must be a day the classroom's weekly class runs (its
-- weekday, inside the series' range, not a cancelled day). Unlike regular
-- occurrences, the 29th-31st are allowed: the calendar shows a standalone
-- make-up slot at the usual class time there.

create table if not exists public.makeup_plans (
  id bigint generated by default as identity primary key,
  classroom_id bigint not null references public.classrooms (id) on delete cascade,
  missed_date date not null,
  student_id bigint references public.students (id) on delete cascade,
  missed_minutes integer not null check (missed_minutes between 1 and 600),
  notes text,
  created_by bigint references public.teachers (id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- One plan per missed date per scope (whole class, or each student).
create unique index if not exists makeup_plans_scope_unique
on public.makeup_plans (classroom_id, missed_date, coalesce(student_id, 0));

create table if not exists public.makeup_sessions (
  id bigint generated by default as identity primary key,
  plan_id bigint not null references public.makeup_plans (id) on delete cascade,
  session_date date not null,
  extra_minutes integer not null check (extra_minutes between 1 and 600),
  unique (plan_id, session_date)
);

create index if not exists makeup_sessions_date_idx
on public.makeup_sessions (session_date);

drop trigger if exists set_makeup_plans_updated_at on public.makeup_plans;
create trigger set_makeup_plans_updated_at
before update on public.makeup_plans
for each row execute function public.set_current_timestamp_updated_at();

alter table public.makeup_plans enable row level security;
alter table public.makeup_sessions enable row level security;

-- Admins see everything; a teacher sees plans for any classroom they run a
-- schedule for (including the earlier part of a series handed over).
-- Writes go through the RPCs below only.
drop policy if exists "makeup_plans_select_scoped" on public.makeup_plans;
create policy "makeup_plans_select_scoped"
on public.makeup_plans
for select
to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.schedules s
    where s.classroom_id = makeup_plans.classroom_id
      and s.teacher_id = public.current_teacher_id()
  )
);

drop policy if exists "makeup_sessions_select_scoped" on public.makeup_sessions;
create policy "makeup_sessions_select_scoped"
on public.makeup_sessions
for select
to authenticated
using (
  exists (
    select 1 from public.makeup_plans p
    where p.id = makeup_sessions.plan_id
  )
);

create or replace function public.save_makeup_plan(
  p_plan_id bigint,
  p_classroom_id bigint,
  p_missed_date date,
  p_student_id bigint,
  p_missed_minutes integer,
  p_notes text,
  p_sessions jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_classroom public.classrooms%rowtype;
  v_student_name text;
  v_plan public.makeup_plans%rowtype;
  v_plan_id bigint;
  v_item jsonb;
  v_date date;
  v_minutes integer;
  v_total integer := 0;
  v_count integer := 0;
begin
  if not public.is_admin() then
    raise exception 'Only admins can arrange make-up classes.';
  end if;

  select * into v_classroom
  from public.classrooms
  where id = p_classroom_id;

  if not found or v_classroom.status <> 'active' or v_classroom.category <> 'regular' then
    raise exception 'Make-ups can only be arranged for an active regular classroom.';
  end if;

  if p_missed_date is null then
    raise exception 'Pick the date being made up.';
  end if;

  if p_missed_minutes is null or p_missed_minutes not between 1 and 600 then
    raise exception 'Minutes to make up must be between 1 and 600.';
  end if;

  if p_student_id is not null then
    select full_name into v_student_name
    from public.students
    where id = p_student_id
      and classroom_id = p_classroom_id;

    if not found then
      raise exception 'That student is not in this classroom.';
    end if;
  end if;

  if jsonb_typeof(p_sessions) <> 'array' or jsonb_array_length(p_sessions) = 0 then
    raise exception 'Add at least one make-up session.';
  end if;

  if p_plan_id is null then
    insert into public.makeup_plans (
      classroom_id, missed_date, student_id, missed_minutes, notes, created_by
    )
    values (
      p_classroom_id, p_missed_date, p_student_id, p_missed_minutes,
      nullif(trim(coalesce(p_notes, '')), ''), public.current_teacher_id()
    )
    returning id into v_plan_id;
  else
    select * into v_plan
    from public.makeup_plans
    where id = p_plan_id
    for update;

    if not found then
      raise exception 'Make-up plan not found.';
    end if;

    if v_plan.classroom_id <> p_classroom_id then
      raise exception 'A make-up plan cannot move to another classroom.';
    end if;

    update public.makeup_plans
    set missed_date = p_missed_date,
        student_id = p_student_id,
        missed_minutes = p_missed_minutes,
        notes = nullif(trim(coalesce(p_notes, '')), '')
    where id = p_plan_id;

    delete from public.makeup_sessions where plan_id = p_plan_id;
    v_plan_id := p_plan_id;
  end if;

  for v_item in select value from jsonb_array_elements(p_sessions)
  loop
    v_date := (v_item ->> 'session_date')::date;
    v_minutes := (v_item ->> 'extra_minutes')::integer;

    if v_date is null then
      raise exception 'Every make-up session needs a date.';
    end if;

    if v_minutes is null or v_minutes not between 1 and 600 then
      raise exception 'Extra minutes must be between 1 and 600 (on %).', v_date;
    end if;

    if not exists (
      select 1 from public.schedules s
      where s.classroom_id = p_classroom_id
        and s.event_type = 'regular'
        and s.status = 'active'
        and s.day_of_week = extract(dow from v_date)::int
        and v_date >= s.start_recur
        and (s.end_recur is null or v_date <= s.end_recur)
        and not exists (
          select 1 from public.schedule_exceptions e
          where e.schedule_id = s.id
            and e.exception_date = v_date
        )
    ) then
      raise exception 'This class does not run on % (or that day is cancelled).', v_date;
    end if;

    begin
      insert into public.makeup_sessions (plan_id, session_date, extra_minutes)
      values (v_plan_id, v_date, v_minutes);
    exception
      when unique_violation then
        raise exception 'The date % is listed twice.', v_date;
    end;

    v_total := v_total + v_minutes;
    v_count := v_count + 1;
  end loop;

  perform public.record_admin_activity(
    case when p_plan_id is null then 'makeup_planned' else 'makeup_updated' end,
    'classroom',
    p_classroom_id,
    v_classroom.name,
    jsonb_build_object(
      'plan_id', v_plan_id,
      'missed_date', p_missed_date,
      'student_id', p_student_id,
      'student_name', v_student_name,
      'missed_minutes', p_missed_minutes,
      'planned_minutes', v_total,
      'sessions', v_count
    )
  );

  return v_plan_id;
exception
  when unique_violation then
    raise exception 'A make-up plan for % already exists for this %. Edit that one instead.',
      p_missed_date,
      case when p_student_id is null then 'class' else 'student' end;
end;
$$;

create or replace function public.delete_makeup_plan(
  p_plan_id bigint
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_plan public.makeup_plans%rowtype;
  v_classroom_name text;
begin
  if not public.is_admin() then
    raise exception 'Only admins can delete make-up plans.';
  end if;

  select * into v_plan
  from public.makeup_plans
  where id = p_plan_id;

  if not found then
    raise exception 'Make-up plan not found.';
  end if;

  select name into v_classroom_name
  from public.classrooms
  where id = v_plan.classroom_id;

  delete from public.makeup_plans where id = p_plan_id;

  perform public.record_admin_activity(
    'makeup_deleted',
    'classroom',
    v_plan.classroom_id,
    coalesce(v_classroom_name, 'Classroom'),
    jsonb_build_object(
      'plan_id', p_plan_id,
      'missed_date', v_plan.missed_date,
      'student_id', v_plan.student_id
    )
  );
end;
$$;

-- A cancelled day with a whole-class make-up plan cannot be restored
-- without removing the plan first, or the class would be both held and
-- made up.
create or replace function public.restore_schedule_occurrence(
  p_schedule_id bigint,
  p_occurrence_date date
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_schedule public.schedules%rowtype;
  v_deleted integer;
begin
  if not public.is_admin() then
    raise exception 'Only admins can restore a class occurrence.';
  end if;

  select * into v_schedule from public.schedules where id = p_schedule_id;

  if not found then
    raise exception 'Schedule not found.';
  end if;

  if v_schedule.classroom_id is not null and exists (
    select 1 from public.makeup_plans
    where classroom_id = v_schedule.classroom_id
      and missed_date = p_occurrence_date
      and student_id is null
  ) then
    raise exception 'This day has a make-up plan. Delete the make-up plan first, then restore the class.';
  end if;

  delete from public.schedule_exceptions
  where schedule_id = p_schedule_id
    and exception_date = p_occurrence_date;

  get diagnostics v_deleted = row_count;

  if v_deleted > 0 then
    perform public.record_admin_activity(
      'schedule_occurrence_restored',
      'schedule',
      p_schedule_id,
      v_schedule.title,
      jsonb_build_object('occurrence_date', p_occurrence_date)
    );
  end if;
end;
$$;

revoke all on function public.save_makeup_plan(bigint, bigint, date, bigint, integer, text, jsonb) from public, anon;
grant execute on function public.save_makeup_plan(bigint, bigint, date, bigint, integer, text, jsonb) to authenticated;
revoke all on function public.delete_makeup_plan(bigint) from public, anon;
grant execute on function public.delete_makeup_plan(bigint) to authenticated;
revoke all on function public.restore_schedule_occurrence(bigint, date) from public, anon;
grant execute on function public.restore_schedule_occurrence(bigint, date) to authenticated;

-- Housekeeping flagged by the security advisor:
-- a trigger function never needs EXECUTE to fire, so nobody should be able
-- to call it over the API; and pin the updated_at helper's search_path.
revoke all on function public.block_lesson_log_on_cancelled_occurrence() from public, anon, authenticated;
alter function public.set_current_timestamp_updated_at() set search_path = public;
